### ISSUE TITLE
Create a release

### ISSUE THREAD

**Issue by helmesjo** [mikekazakov/pstld#1]
Hi! Just found this and gave it a spin. It indeed works for the (limited) use case I have atm, and want to package it as a [build2](https://build2.org) package. Though for this it sure would be better if there is a release tag I can rely on.

Thanks!

**Comment by mikekazakov** [comment]
Hi! I can create an arbitrary release like v0.1 from the current sources - would that be enough?

**Comment by helmesjo** [comment]
Absolutely!

**Comment by mikekazakov** [comment]
Done: https://github.com/mikekazakov/pstld/releases/tag/0.1.0

**Comment by helmesjo** [comment]
FYI I've publish it as a `build2` package now: https://queue.cppget.org/pstld?q=pstld
Package repo can be found here: https://github.com/build2-packaging/pstld

**Comment by mikekazakov** [comment]
Great, thanks!
