### ISSUE TITLE
[suggestion] Define __cpp_lib_execution & __cpp_lib_parallel_algorithm

### ISSUE THREAD

**Issue by helmesjo** [mikekazakov/pstld#2]
Hi! Just thought it would be convenient (since `PSTLD_HACK_INTO_STD` already exists for "seamless integration"), I think these could also be defined if so (or another define for the latter).

Thanks!

**Comment by mikekazakov** [comment]
Hi, I'm not exactly sure about the semantics of these availability macros.
Do they assert that the functionality exists or that the according header exists?
If the latter is true this could potentially break some code...

**Comment by helmesjo** [comment]
These are _[feature-test macros](https://en.cppreference.com/w/cpp/utility/feature_test)_ and should indicate that it's implemented (and AFAIK that the corresponding header is available). The latter isn't true in this case, but arguably if you are using this library & explicitly define `PSTLD_HACK_INTO_STD` you'd be aware of this (because you already included the `pstdl` header).
