### ISSUE TITLE
Missing include <atomic>

### ISSUE THREAD

**Issue by helmesjo** [mikekazakov/pstld#4]
Hi again!

When building with clang on macos (not apple-clang) it fails with:
`pstld/pstld.h:402:10: error: no type named 'atomic_int64_t' in namespace 'std'`

`pstld.h` is just missing an include of `<atomic>`.

If possible, it'd be great with a `v0.1.2` release. (:

Thanks!

**Comment by mikekazakov** [comment]
Done: https://github.com/mikekazakov/pstld/releases/tag/0.1.2
